-- Cache de consultas consolidadas de mercado
CREATE TABLE IF NOT EXISTS public.card_prices (
    search_key TEXT PRIMARY KEY,
    card_name TEXT NOT NULL,
    card_set TEXT,
    card_number TEXT,
    card_condition TEXT,
    card_finish TEXT,
    card_language TEXT,
    result JSONB NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.card_prices
    ADD COLUMN IF NOT EXISTS card_name TEXT,
    ADD COLUMN IF NOT EXISTS card_set TEXT,
    ADD COLUMN IF NOT EXISTS card_number TEXT,
    ADD COLUMN IF NOT EXISTS card_condition TEXT,
    ADD COLUMN IF NOT EXISTS card_finish TEXT,
    ADD COLUMN IF NOT EXISTS card_language TEXT,
    ADD COLUMN IF NOT EXISTS result JSONB,
    ADD COLUMN IF NOT EXISTS fetched_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

UPDATE public.card_prices
SET result = '{}'::jsonb
WHERE result IS NULL;

ALTER TABLE public.card_prices
    ALTER COLUMN result SET DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_card_prices_fetched_at
    ON public.card_prices (fetched_at DESC);

-- Historico de snapshots de preco para grafico
CREATE TABLE IF NOT EXISTS public.price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id TEXT NOT NULL,
    store_name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    match_type TEXT,
    variant_label TEXT,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_price_history_card_id_recorded_at
    ON public.price_history (card_id, recorded_at DESC);
