-- Price integrity metadata. Suspicious offers remain purchasable, but do not
-- influence the public index until a real payment/delivery confirms the sale.
ALTER TABLE public.seller_listings
    ADD COLUMN IF NOT EXISTS price_risk_level text NOT NULL DEFAULT 'normal'
        CHECK (price_risk_level IN ('normal', 'attention', 'high')),
    ADD COLUMN IF NOT EXISTS price_risk_reason text,
    ADD COLUMN IF NOT EXISTS reference_price numeric(12,2),
    ADD COLUMN IF NOT EXISTS index_eligible boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS risk_assessed_at timestamptz;

CREATE INDEX IF NOT EXISTS seller_listings_index_eligible_idx
    ON public.seller_listings (card_id, status, index_eligible);

CREATE TABLE IF NOT EXISTS public.tcg_hub_price_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id text NOT NULL,
    card_condition text,
    card_finish text,
    card_language text,
    index_price numeric(12,2),
    fair_low numeric(12,2),
    fair_high numeric(12,2),
    confidence text NOT NULL CHECK (confidence IN ('insufficient', 'low', 'medium', 'high')),
    sample_size integer NOT NULL DEFAULT 0,
    verified_sales integer NOT NULL DEFAULT 0,
    excluded_outliers integer NOT NULL DEFAULT 0,
    methodology text NOT NULL DEFAULT 'weighted_median_v1',
    calculated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.tcg_hub_price_snapshots ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS tcg_hub_price_snapshots_lookup_idx
    ON public.tcg_hub_price_snapshots
    (card_id, card_condition, card_finish, card_language, calculated_at DESC);

COMMENT ON TABLE public.tcg_hub_price_snapshots IS
    'Versioned, auditable snapshots of the independent TCG Hub price index.';
