ALTER TABLE public.seller_listings
    ADD COLUMN IF NOT EXISTS moderation_status text NOT NULL DEFAULT 'clear'
        CHECK (moderation_status IN ('clear', 'pending', 'approved', 'excluded', 'suspended')),
    ADD COLUMN IF NOT EXISTS reviewed_at timestamptz,
    ADD COLUMN IF NOT EXISTS reviewed_by uuid REFERENCES auth.users(id);

UPDATE public.seller_listings
SET moderation_status = CASE
    WHEN price_risk_level IN ('attention', 'high') THEN 'pending'
    ELSE 'clear'
END
WHERE moderation_status = 'clear';

CREATE TABLE IF NOT EXISTS public.listing_moderation_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id uuid NOT NULL REFERENCES public.seller_listings(id) ON DELETE CASCADE,
    moderator_id uuid NOT NULL REFERENCES auth.users(id),
    action text NOT NULL CHECK (action IN ('approved', 'excluded', 'suspended', 'restored')),
    reason text,
    previous_status text,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.listing_moderation_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.listing_moderation_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.listing_moderation_events TO service_role;

CREATE INDEX IF NOT EXISTS seller_listings_moderation_queue_idx
    ON public.seller_listings (moderation_status, price_risk_level, risk_assessed_at DESC);
CREATE INDEX IF NOT EXISTS listing_moderation_events_listing_idx
    ON public.listing_moderation_events (listing_id, created_at DESC);
